//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by SlSvcUtil, version 5.0.61118.0
// 


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IService")]
public interface IService
{
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/getMsg", ReplyAction="http://tempuri.org/IService/getMsgResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.IAsyncResult BegingetMsg(getMsgRequest request, System.AsyncCallback callback, object asyncState);
    
    getMsgResponse EndgetMsg(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/setMsg", ReplyAction="http://tempuri.org/IService/setMsgResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.IAsyncResult BeginsetMsg(setMsgRequest request, System.AsyncCallback callback, object asyncState);
    
    setMsgResponse EndsetMsg(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/getData", ReplyAction="http://tempuri.org/IService/getDataResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
    System.IAsyncResult BegingetData(getDataRequest request, System.AsyncCallback callback, object asyncState);
    
    getDataResponse EndgetData(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/setData", ReplyAction="http://tempuri.org/IService/setDataResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
    System.IAsyncResult BeginsetData(setDataRequest request, System.AsyncCallback callback, object asyncState);
    
    setDataResponse EndsetData(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/GetList", ReplyAction="http://tempuri.org/IService/GetListResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
    System.IAsyncResult BeginGetList(GetListRequest request, System.AsyncCallback callback, object asyncState);
    
    GetListResponse EndGetList(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/PadCarID", ReplyAction="http://tempuri.org/IService/PadCarIDResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
    System.IAsyncResult BeginPadCarID(PadCarIDRequest request, System.AsyncCallback callback, object asyncState);
    
    PadCarIDResponse EndPadCarID(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/GetWorkingList", ReplyAction="http://tempuri.org/IService/GetWorkingListResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
    System.IAsyncResult BeginGetWorkingList(GetWorkingListRequest request, System.AsyncCallback callback, object asyncState);
    
    GetWorkingListResponse EndGetWorkingList(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/GetEmpDay", ReplyAction="http://tempuri.org/IService/GetEmpDayResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
    System.IAsyncResult BeginGetEmpDay(GetEmpDayRequest request, System.AsyncCallback callback, object asyncState);
    
    GetEmpDayResponse EndGetEmpDay(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/GetEmpMonth", ReplyAction="http://tempuri.org/IService/GetEmpMonthResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
    System.IAsyncResult BeginGetEmpMonth(GetEmpMonthRequest request, System.AsyncCallback callback, object asyncState);
    
    GetEmpMonthResponse EndGetEmpMonth(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/GetJson", ReplyAction="http://tempuri.org/IService/GetJsonResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
    System.IAsyncResult BeginGetJson(GetJsonRequest request, System.AsyncCallback callback, object asyncState);
    
    GetJsonResponse EndGetJson(System.IAsyncResult result);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getMsg", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class getMsgRequest
{
    
    public getMsgRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getMsgResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class getMsgResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string getMsgResult;
    
    public getMsgResponse()
    {
    }
    
    public getMsgResponse(string getMsgResult)
    {
        this.getMsgResult = getMsgResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="setMsg", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class setMsgRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string msg;
    
    public setMsgRequest()
    {
    }
    
    public setMsgRequest(string msg)
    {
        this.msg = msg;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="setMsgResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class setMsgResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string setMsgResult;
    
    public setMsgResponse()
    {
    }
    
    public setMsgResponse(string setMsgResult)
    {
        this.setMsgResult = setMsgResult;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("SlSvcUtil", "5.0.61118.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Host")]
public partial class Data
{
    
    private string nameField;
    
    private int ageField;
    
    private bool ageFieldSpecified;
    
    private string[] arrayField;
    
    private string msgField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public int age
    {
        get
        {
            return this.ageField;
        }
        set
        {
            this.ageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ageSpecified
    {
        get
        {
            return this.ageFieldSpecified;
        }
        set
        {
            this.ageFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public string[] array
    {
        get
        {
            return this.arrayField;
        }
        set
        {
            this.arrayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
    public string msg
    {
        get
        {
            return this.msgField;
        }
        set
        {
            this.msgField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class getDataRequest
{
    
    public getDataRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class getDataResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Data getDataResult;
    
    public getDataResponse()
    {
    }
    
    public getDataResponse(Data getDataResult)
    {
        this.getDataResult = getDataResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="setData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class setDataRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Data data;
    
    public setDataRequest()
    {
    }
    
    public setDataRequest(Data data)
    {
        this.data = data;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="setDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class setDataResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Data setDataResult;
    
    public setDataResponse()
    {
    }
    
    public setDataResponse(Data setDataResult)
    {
        this.setDataResult = setDataResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetListRequest
{
    
    public GetListRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetListResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public ArrayOfXElement GetListResult;
    
    public GetListResponse()
    {
    }
    
    public GetListResponse(ArrayOfXElement GetListResult)
    {
        this.GetListResult = GetListResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="PadCarID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class PadCarIDRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string CarID;
    
    public PadCarIDRequest()
    {
    }
    
    public PadCarIDRequest(string CarID)
    {
        this.CarID = CarID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="PadCarIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class PadCarIDResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PadCarIDResult;
    
    public PadCarIDResponse()
    {
    }
    
    public PadCarIDResponse(string PadCarIDResult)
    {
        this.PadCarIDResult = PadCarIDResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetWorkingList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetWorkingListRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string CarID;
    
    public GetWorkingListRequest()
    {
    }
    
    public GetWorkingListRequest(string CarID)
    {
        this.CarID = CarID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetWorkingListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetWorkingListResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string GetWorkingListResult;
    
    public GetWorkingListResponse()
    {
    }
    
    public GetWorkingListResponse(string GetWorkingListResult)
    {
        this.GetWorkingListResult = GetWorkingListResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetEmpDay", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetEmpDayRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string CarID;
    
    public GetEmpDayRequest()
    {
    }
    
    public GetEmpDayRequest(string CarID)
    {
        this.CarID = CarID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetEmpDayResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetEmpDayResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string GetEmpDayResult;
    
    public GetEmpDayResponse()
    {
    }
    
    public GetEmpDayResponse(string GetEmpDayResult)
    {
        this.GetEmpDayResult = GetEmpDayResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetEmpMonth", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetEmpMonthRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string CarID;
    
    public GetEmpMonthRequest()
    {
    }
    
    public GetEmpMonthRequest(string CarID)
    {
        this.CarID = CarID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetEmpMonthResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetEmpMonthResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string GetEmpMonthResult;
    
    public GetEmpMonthResponse()
    {
    }
    
    public GetEmpMonthResponse(string GetEmpMonthResult)
    {
        this.GetEmpMonthResult = GetEmpMonthResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetJson", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetJsonRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Bll;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Exc;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public object[] par;
    
    public GetJsonRequest()
    {
    }
    
    public GetJsonRequest(string Bll, string Exc, object[] par)
    {
        this.Bll = Bll;
        this.Exc = Exc;
        this.par = par;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetJsonResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetJsonResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
    public byte[] GetJsonResult;
    
    public GetJsonResponse()
    {
    }
    
    public GetJsonResponse(byte[] GetJsonResult)
    {
        this.GetJsonResult = GetJsonResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServiceChannel : IService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class getMsgCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public getMsgCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class setMsgCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public setMsgCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class getDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public getDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public Data Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((Data)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class setDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public setDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public Data Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((Data)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public ArrayOfXElement Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((ArrayOfXElement)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class PadCarIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public PadCarIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetWorkingListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetWorkingListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetEmpDayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetEmpDayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetEmpMonthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetEmpMonthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public byte[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((byte[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServiceClient : System.ServiceModel.ClientBase<IService>, IService
{
    
    private BeginOperationDelegate onBegingetMsgDelegate;
    
    private EndOperationDelegate onEndgetMsgDelegate;
    
    private System.Threading.SendOrPostCallback ongetMsgCompletedDelegate;
    
    private BeginOperationDelegate onBeginsetMsgDelegate;
    
    private EndOperationDelegate onEndsetMsgDelegate;
    
    private System.Threading.SendOrPostCallback onsetMsgCompletedDelegate;
    
    private BeginOperationDelegate onBegingetDataDelegate;
    
    private EndOperationDelegate onEndgetDataDelegate;
    
    private System.Threading.SendOrPostCallback ongetDataCompletedDelegate;
    
    private BeginOperationDelegate onBeginsetDataDelegate;
    
    private EndOperationDelegate onEndsetDataDelegate;
    
    private System.Threading.SendOrPostCallback onsetDataCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetListDelegate;
    
    private EndOperationDelegate onEndGetListDelegate;
    
    private System.Threading.SendOrPostCallback onGetListCompletedDelegate;
    
    private BeginOperationDelegate onBeginPadCarIDDelegate;
    
    private EndOperationDelegate onEndPadCarIDDelegate;
    
    private System.Threading.SendOrPostCallback onPadCarIDCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetWorkingListDelegate;
    
    private EndOperationDelegate onEndGetWorkingListDelegate;
    
    private System.Threading.SendOrPostCallback onGetWorkingListCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetEmpDayDelegate;
    
    private EndOperationDelegate onEndGetEmpDayDelegate;
    
    private System.Threading.SendOrPostCallback onGetEmpDayCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetEmpMonthDelegate;
    
    private EndOperationDelegate onEndGetEmpMonthDelegate;
    
    private System.Threading.SendOrPostCallback onGetEmpMonthCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetJsonDelegate;
    
    private EndOperationDelegate onEndGetJsonDelegate;
    
    private System.Threading.SendOrPostCallback onGetJsonCompletedDelegate;
    
    private BeginOperationDelegate onBeginOpenDelegate;
    
    private EndOperationDelegate onEndOpenDelegate;
    
    private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
    
    private BeginOperationDelegate onBeginCloseDelegate;
    
    private EndOperationDelegate onEndCloseDelegate;
    
    private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
    
    public ServiceClient()
    {
    }
    
    public ServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Net.CookieContainer CookieContainer
    {
        get
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                return httpCookieContainerManager.CookieContainer;
            }
            else
            {
                return null;
            }
        }
        set
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                httpCookieContainerManager.CookieContainer = value;
            }
            else
            {
                throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                        "ookieContainerBindingElement.");
            }
        }
    }
    
    public event System.EventHandler<getMsgCompletedEventArgs> getMsgCompleted;
    
    public event System.EventHandler<setMsgCompletedEventArgs> setMsgCompleted;
    
    public event System.EventHandler<getDataCompletedEventArgs> getDataCompleted;
    
    public event System.EventHandler<setDataCompletedEventArgs> setDataCompleted;
    
    public event System.EventHandler<GetListCompletedEventArgs> GetListCompleted;
    
    public event System.EventHandler<PadCarIDCompletedEventArgs> PadCarIDCompleted;
    
    public event System.EventHandler<GetWorkingListCompletedEventArgs> GetWorkingListCompleted;
    
    public event System.EventHandler<GetEmpDayCompletedEventArgs> GetEmpDayCompleted;
    
    public event System.EventHandler<GetEmpMonthCompletedEventArgs> GetEmpMonthCompleted;
    
    public event System.EventHandler<GetJsonCompletedEventArgs> GetJsonCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService.BegingetMsg(getMsgRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BegingetMsg(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private System.IAsyncResult BegingetMsg(System.AsyncCallback callback, object asyncState)
    {
        getMsgRequest inValue = new getMsgRequest();
        return ((IService)(this)).BegingetMsg(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getMsgResponse IService.EndgetMsg(System.IAsyncResult result)
    {
        return base.Channel.EndgetMsg(result);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private string EndgetMsg(System.IAsyncResult result)
    {
        getMsgResponse retVal = ((IService)(this)).EndgetMsg(result);
        return retVal.getMsgResult;
    }
    
    private System.IAsyncResult OnBegingetMsg(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return this.BegingetMsg(callback, asyncState);
    }
    
    private object[] OnEndgetMsg(System.IAsyncResult result)
    {
        string retVal = this.EndgetMsg(result);
        return new object[] {
                retVal};
    }
    
    private void OngetMsgCompleted(object state)
    {
        if ((this.getMsgCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.getMsgCompleted(this, new getMsgCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void getMsgAsync()
    {
        this.getMsgAsync(null);
    }
    
    public void getMsgAsync(object userState)
    {
        if ((this.onBegingetMsgDelegate == null))
        {
            this.onBegingetMsgDelegate = new BeginOperationDelegate(this.OnBegingetMsg);
        }
        if ((this.onEndgetMsgDelegate == null))
        {
            this.onEndgetMsgDelegate = new EndOperationDelegate(this.OnEndgetMsg);
        }
        if ((this.ongetMsgCompletedDelegate == null))
        {
            this.ongetMsgCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetMsgCompleted);
        }
        base.InvokeAsync(this.onBegingetMsgDelegate, null, this.onEndgetMsgDelegate, this.ongetMsgCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService.BeginsetMsg(setMsgRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginsetMsg(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private System.IAsyncResult BeginsetMsg(string msg, System.AsyncCallback callback, object asyncState)
    {
        setMsgRequest inValue = new setMsgRequest();
        inValue.msg = msg;
        return ((IService)(this)).BeginsetMsg(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    setMsgResponse IService.EndsetMsg(System.IAsyncResult result)
    {
        return base.Channel.EndsetMsg(result);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private string EndsetMsg(System.IAsyncResult result)
    {
        setMsgResponse retVal = ((IService)(this)).EndsetMsg(result);
        return retVal.setMsgResult;
    }
    
    private System.IAsyncResult OnBeginsetMsg(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string msg = ((string)(inValues[0]));
        return this.BeginsetMsg(msg, callback, asyncState);
    }
    
    private object[] OnEndsetMsg(System.IAsyncResult result)
    {
        string retVal = this.EndsetMsg(result);
        return new object[] {
                retVal};
    }
    
    private void OnsetMsgCompleted(object state)
    {
        if ((this.setMsgCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.setMsgCompleted(this, new setMsgCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void setMsgAsync(string msg)
    {
        this.setMsgAsync(msg, null);
    }
    
    public void setMsgAsync(string msg, object userState)
    {
        if ((this.onBeginsetMsgDelegate == null))
        {
            this.onBeginsetMsgDelegate = new BeginOperationDelegate(this.OnBeginsetMsg);
        }
        if ((this.onEndsetMsgDelegate == null))
        {
            this.onEndsetMsgDelegate = new EndOperationDelegate(this.OnEndsetMsg);
        }
        if ((this.onsetMsgCompletedDelegate == null))
        {
            this.onsetMsgCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnsetMsgCompleted);
        }
        base.InvokeAsync(this.onBeginsetMsgDelegate, new object[] {
                    msg}, this.onEndsetMsgDelegate, this.onsetMsgCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService.BegingetData(getDataRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BegingetData(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private System.IAsyncResult BegingetData(System.AsyncCallback callback, object asyncState)
    {
        getDataRequest inValue = new getDataRequest();
        return ((IService)(this)).BegingetData(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getDataResponse IService.EndgetData(System.IAsyncResult result)
    {
        return base.Channel.EndgetData(result);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private Data EndgetData(System.IAsyncResult result)
    {
        getDataResponse retVal = ((IService)(this)).EndgetData(result);
        return retVal.getDataResult;
    }
    
    private System.IAsyncResult OnBegingetData(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return this.BegingetData(callback, asyncState);
    }
    
    private object[] OnEndgetData(System.IAsyncResult result)
    {
        Data retVal = this.EndgetData(result);
        return new object[] {
                retVal};
    }
    
    private void OngetDataCompleted(object state)
    {
        if ((this.getDataCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.getDataCompleted(this, new getDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void getDataAsync()
    {
        this.getDataAsync(null);
    }
    
    public void getDataAsync(object userState)
    {
        if ((this.onBegingetDataDelegate == null))
        {
            this.onBegingetDataDelegate = new BeginOperationDelegate(this.OnBegingetData);
        }
        if ((this.onEndgetDataDelegate == null))
        {
            this.onEndgetDataDelegate = new EndOperationDelegate(this.OnEndgetData);
        }
        if ((this.ongetDataCompletedDelegate == null))
        {
            this.ongetDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetDataCompleted);
        }
        base.InvokeAsync(this.onBegingetDataDelegate, null, this.onEndgetDataDelegate, this.ongetDataCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService.BeginsetData(setDataRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginsetData(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private System.IAsyncResult BeginsetData(Data data, System.AsyncCallback callback, object asyncState)
    {
        setDataRequest inValue = new setDataRequest();
        inValue.data = data;
        return ((IService)(this)).BeginsetData(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    setDataResponse IService.EndsetData(System.IAsyncResult result)
    {
        return base.Channel.EndsetData(result);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private Data EndsetData(System.IAsyncResult result)
    {
        setDataResponse retVal = ((IService)(this)).EndsetData(result);
        return retVal.setDataResult;
    }
    
    private System.IAsyncResult OnBeginsetData(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        Data data = ((Data)(inValues[0]));
        return this.BeginsetData(data, callback, asyncState);
    }
    
    private object[] OnEndsetData(System.IAsyncResult result)
    {
        Data retVal = this.EndsetData(result);
        return new object[] {
                retVal};
    }
    
    private void OnsetDataCompleted(object state)
    {
        if ((this.setDataCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.setDataCompleted(this, new setDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void setDataAsync(Data data)
    {
        this.setDataAsync(data, null);
    }
    
    public void setDataAsync(Data data, object userState)
    {
        if ((this.onBeginsetDataDelegate == null))
        {
            this.onBeginsetDataDelegate = new BeginOperationDelegate(this.OnBeginsetData);
        }
        if ((this.onEndsetDataDelegate == null))
        {
            this.onEndsetDataDelegate = new EndOperationDelegate(this.OnEndsetData);
        }
        if ((this.onsetDataCompletedDelegate == null))
        {
            this.onsetDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnsetDataCompleted);
        }
        base.InvokeAsync(this.onBeginsetDataDelegate, new object[] {
                    data}, this.onEndsetDataDelegate, this.onsetDataCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService.BeginGetList(GetListRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetList(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private System.IAsyncResult BeginGetList(System.AsyncCallback callback, object asyncState)
    {
        GetListRequest inValue = new GetListRequest();
        return ((IService)(this)).BeginGetList(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetListResponse IService.EndGetList(System.IAsyncResult result)
    {
        return base.Channel.EndGetList(result);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private ArrayOfXElement EndGetList(System.IAsyncResult result)
    {
        GetListResponse retVal = ((IService)(this)).EndGetList(result);
        return retVal.GetListResult;
    }
    
    private System.IAsyncResult OnBeginGetList(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginGetList(callback, asyncState);
    }
    
    private object[] OnEndGetList(System.IAsyncResult result)
    {
        ArrayOfXElement retVal = this.EndGetList(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetListCompleted(object state)
    {
        if ((this.GetListCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetListCompleted(this, new GetListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetListAsync()
    {
        this.GetListAsync(null);
    }
    
    public void GetListAsync(object userState)
    {
        if ((this.onBeginGetListDelegate == null))
        {
            this.onBeginGetListDelegate = new BeginOperationDelegate(this.OnBeginGetList);
        }
        if ((this.onEndGetListDelegate == null))
        {
            this.onEndGetListDelegate = new EndOperationDelegate(this.OnEndGetList);
        }
        if ((this.onGetListCompletedDelegate == null))
        {
            this.onGetListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetListCompleted);
        }
        base.InvokeAsync(this.onBeginGetListDelegate, null, this.onEndGetListDelegate, this.onGetListCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService.BeginPadCarID(PadCarIDRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginPadCarID(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private System.IAsyncResult BeginPadCarID(string CarID, System.AsyncCallback callback, object asyncState)
    {
        PadCarIDRequest inValue = new PadCarIDRequest();
        inValue.CarID = CarID;
        return ((IService)(this)).BeginPadCarID(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    PadCarIDResponse IService.EndPadCarID(System.IAsyncResult result)
    {
        return base.Channel.EndPadCarID(result);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private string EndPadCarID(System.IAsyncResult result)
    {
        PadCarIDResponse retVal = ((IService)(this)).EndPadCarID(result);
        return retVal.PadCarIDResult;
    }
    
    private System.IAsyncResult OnBeginPadCarID(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string CarID = ((string)(inValues[0]));
        return this.BeginPadCarID(CarID, callback, asyncState);
    }
    
    private object[] OnEndPadCarID(System.IAsyncResult result)
    {
        string retVal = this.EndPadCarID(result);
        return new object[] {
                retVal};
    }
    
    private void OnPadCarIDCompleted(object state)
    {
        if ((this.PadCarIDCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.PadCarIDCompleted(this, new PadCarIDCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void PadCarIDAsync(string CarID)
    {
        this.PadCarIDAsync(CarID, null);
    }
    
    public void PadCarIDAsync(string CarID, object userState)
    {
        if ((this.onBeginPadCarIDDelegate == null))
        {
            this.onBeginPadCarIDDelegate = new BeginOperationDelegate(this.OnBeginPadCarID);
        }
        if ((this.onEndPadCarIDDelegate == null))
        {
            this.onEndPadCarIDDelegate = new EndOperationDelegate(this.OnEndPadCarID);
        }
        if ((this.onPadCarIDCompletedDelegate == null))
        {
            this.onPadCarIDCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPadCarIDCompleted);
        }
        base.InvokeAsync(this.onBeginPadCarIDDelegate, new object[] {
                    CarID}, this.onEndPadCarIDDelegate, this.onPadCarIDCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService.BeginGetWorkingList(GetWorkingListRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetWorkingList(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private System.IAsyncResult BeginGetWorkingList(string CarID, System.AsyncCallback callback, object asyncState)
    {
        GetWorkingListRequest inValue = new GetWorkingListRequest();
        inValue.CarID = CarID;
        return ((IService)(this)).BeginGetWorkingList(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetWorkingListResponse IService.EndGetWorkingList(System.IAsyncResult result)
    {
        return base.Channel.EndGetWorkingList(result);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private string EndGetWorkingList(System.IAsyncResult result)
    {
        GetWorkingListResponse retVal = ((IService)(this)).EndGetWorkingList(result);
        return retVal.GetWorkingListResult;
    }
    
    private System.IAsyncResult OnBeginGetWorkingList(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string CarID = ((string)(inValues[0]));
        return this.BeginGetWorkingList(CarID, callback, asyncState);
    }
    
    private object[] OnEndGetWorkingList(System.IAsyncResult result)
    {
        string retVal = this.EndGetWorkingList(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetWorkingListCompleted(object state)
    {
        if ((this.GetWorkingListCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetWorkingListCompleted(this, new GetWorkingListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetWorkingListAsync(string CarID)
    {
        this.GetWorkingListAsync(CarID, null);
    }
    
    public void GetWorkingListAsync(string CarID, object userState)
    {
        if ((this.onBeginGetWorkingListDelegate == null))
        {
            this.onBeginGetWorkingListDelegate = new BeginOperationDelegate(this.OnBeginGetWorkingList);
        }
        if ((this.onEndGetWorkingListDelegate == null))
        {
            this.onEndGetWorkingListDelegate = new EndOperationDelegate(this.OnEndGetWorkingList);
        }
        if ((this.onGetWorkingListCompletedDelegate == null))
        {
            this.onGetWorkingListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetWorkingListCompleted);
        }
        base.InvokeAsync(this.onBeginGetWorkingListDelegate, new object[] {
                    CarID}, this.onEndGetWorkingListDelegate, this.onGetWorkingListCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService.BeginGetEmpDay(GetEmpDayRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetEmpDay(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private System.IAsyncResult BeginGetEmpDay(string CarID, System.AsyncCallback callback, object asyncState)
    {
        GetEmpDayRequest inValue = new GetEmpDayRequest();
        inValue.CarID = CarID;
        return ((IService)(this)).BeginGetEmpDay(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetEmpDayResponse IService.EndGetEmpDay(System.IAsyncResult result)
    {
        return base.Channel.EndGetEmpDay(result);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private string EndGetEmpDay(System.IAsyncResult result)
    {
        GetEmpDayResponse retVal = ((IService)(this)).EndGetEmpDay(result);
        return retVal.GetEmpDayResult;
    }
    
    private System.IAsyncResult OnBeginGetEmpDay(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string CarID = ((string)(inValues[0]));
        return this.BeginGetEmpDay(CarID, callback, asyncState);
    }
    
    private object[] OnEndGetEmpDay(System.IAsyncResult result)
    {
        string retVal = this.EndGetEmpDay(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetEmpDayCompleted(object state)
    {
        if ((this.GetEmpDayCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetEmpDayCompleted(this, new GetEmpDayCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetEmpDayAsync(string CarID)
    {
        this.GetEmpDayAsync(CarID, null);
    }
    
    public void GetEmpDayAsync(string CarID, object userState)
    {
        if ((this.onBeginGetEmpDayDelegate == null))
        {
            this.onBeginGetEmpDayDelegate = new BeginOperationDelegate(this.OnBeginGetEmpDay);
        }
        if ((this.onEndGetEmpDayDelegate == null))
        {
            this.onEndGetEmpDayDelegate = new EndOperationDelegate(this.OnEndGetEmpDay);
        }
        if ((this.onGetEmpDayCompletedDelegate == null))
        {
            this.onGetEmpDayCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetEmpDayCompleted);
        }
        base.InvokeAsync(this.onBeginGetEmpDayDelegate, new object[] {
                    CarID}, this.onEndGetEmpDayDelegate, this.onGetEmpDayCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService.BeginGetEmpMonth(GetEmpMonthRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetEmpMonth(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private System.IAsyncResult BeginGetEmpMonth(string CarID, System.AsyncCallback callback, object asyncState)
    {
        GetEmpMonthRequest inValue = new GetEmpMonthRequest();
        inValue.CarID = CarID;
        return ((IService)(this)).BeginGetEmpMonth(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetEmpMonthResponse IService.EndGetEmpMonth(System.IAsyncResult result)
    {
        return base.Channel.EndGetEmpMonth(result);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private string EndGetEmpMonth(System.IAsyncResult result)
    {
        GetEmpMonthResponse retVal = ((IService)(this)).EndGetEmpMonth(result);
        return retVal.GetEmpMonthResult;
    }
    
    private System.IAsyncResult OnBeginGetEmpMonth(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string CarID = ((string)(inValues[0]));
        return this.BeginGetEmpMonth(CarID, callback, asyncState);
    }
    
    private object[] OnEndGetEmpMonth(System.IAsyncResult result)
    {
        string retVal = this.EndGetEmpMonth(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetEmpMonthCompleted(object state)
    {
        if ((this.GetEmpMonthCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetEmpMonthCompleted(this, new GetEmpMonthCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetEmpMonthAsync(string CarID)
    {
        this.GetEmpMonthAsync(CarID, null);
    }
    
    public void GetEmpMonthAsync(string CarID, object userState)
    {
        if ((this.onBeginGetEmpMonthDelegate == null))
        {
            this.onBeginGetEmpMonthDelegate = new BeginOperationDelegate(this.OnBeginGetEmpMonth);
        }
        if ((this.onEndGetEmpMonthDelegate == null))
        {
            this.onEndGetEmpMonthDelegate = new EndOperationDelegate(this.OnEndGetEmpMonth);
        }
        if ((this.onGetEmpMonthCompletedDelegate == null))
        {
            this.onGetEmpMonthCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetEmpMonthCompleted);
        }
        base.InvokeAsync(this.onBeginGetEmpMonthDelegate, new object[] {
                    CarID}, this.onEndGetEmpMonthDelegate, this.onGetEmpMonthCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService.BeginGetJson(GetJsonRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetJson(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private System.IAsyncResult BeginGetJson(string Bll, string Exc, object[] par, System.AsyncCallback callback, object asyncState)
    {
        GetJsonRequest inValue = new GetJsonRequest();
        inValue.Bll = Bll;
        inValue.Exc = Exc;
        inValue.par = par;
        return ((IService)(this)).BeginGetJson(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetJsonResponse IService.EndGetJson(System.IAsyncResult result)
    {
        return base.Channel.EndGetJson(result);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private byte[] EndGetJson(System.IAsyncResult result)
    {
        GetJsonResponse retVal = ((IService)(this)).EndGetJson(result);
        return retVal.GetJsonResult;
    }
    
    private System.IAsyncResult OnBeginGetJson(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string Bll = ((string)(inValues[0]));
        string Exc = ((string)(inValues[1]));
        object[] par = ((object[])(inValues[2]));
        return this.BeginGetJson(Bll, Exc, par, callback, asyncState);
    }
    
    private object[] OnEndGetJson(System.IAsyncResult result)
    {
        byte[] retVal = this.EndGetJson(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetJsonCompleted(object state)
    {
        if ((this.GetJsonCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetJsonCompleted(this, new GetJsonCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetJsonAsync(string Bll, string Exc, object[] par)
    {
        this.GetJsonAsync(Bll, Exc, par, null);
    }
    
    public void GetJsonAsync(string Bll, string Exc, object[] par, object userState)
    {
        if ((this.onBeginGetJsonDelegate == null))
        {
            this.onBeginGetJsonDelegate = new BeginOperationDelegate(this.OnBeginGetJson);
        }
        if ((this.onEndGetJsonDelegate == null))
        {
            this.onEndGetJsonDelegate = new EndOperationDelegate(this.OnEndGetJson);
        }
        if ((this.onGetJsonCompletedDelegate == null))
        {
            this.onGetJsonCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetJsonCompleted);
        }
        base.InvokeAsync(this.onBeginGetJsonDelegate, new object[] {
                    Bll,
                    Exc,
                    par}, this.onEndGetJsonDelegate, this.onGetJsonCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
    }
    
    private object[] OnEndOpen(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
        return null;
    }
    
    private void OnOpenCompleted(object state)
    {
        if ((this.OpenCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void OpenAsync()
    {
        this.OpenAsync(null);
    }
    
    public void OpenAsync(object userState)
    {
        if ((this.onBeginOpenDelegate == null))
        {
            this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
        }
        if ((this.onEndOpenDelegate == null))
        {
            this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
        }
        if ((this.onOpenCompletedDelegate == null))
        {
            this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
        }
        base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
    }
    
    private object[] OnEndClose(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
        return null;
    }
    
    private void OnCloseCompleted(object state)
    {
        if ((this.CloseCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void CloseAsync()
    {
        this.CloseAsync(null);
    }
    
    public void CloseAsync(object userState)
    {
        if ((this.onBeginCloseDelegate == null))
        {
            this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
        }
        if ((this.onEndCloseDelegate == null))
        {
            this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
        }
        if ((this.onCloseCompletedDelegate == null))
        {
            this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
        }
        base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
    }
    
    protected override IService CreateChannel()
    {
        return new ServiceClientChannel(this);
    }
    
    private class ServiceClientChannel : ChannelBase<IService>, IService
    {
        
        public ServiceClientChannel(System.ServiceModel.ClientBase<IService> client) : 
                base(client)
        {
        }
        
        public System.IAsyncResult BegingetMsg(getMsgRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("getMsg", _args, callback, asyncState);
            return _result;
        }
        
        public getMsgResponse EndgetMsg(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            getMsgResponse _result = ((getMsgResponse)(base.EndInvoke("getMsg", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginsetMsg(setMsgRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("setMsg", _args, callback, asyncState);
            return _result;
        }
        
        public setMsgResponse EndsetMsg(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            setMsgResponse _result = ((setMsgResponse)(base.EndInvoke("setMsg", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BegingetData(getDataRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("getData", _args, callback, asyncState);
            return _result;
        }
        
        public getDataResponse EndgetData(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            getDataResponse _result = ((getDataResponse)(base.EndInvoke("getData", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginsetData(setDataRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("setData", _args, callback, asyncState);
            return _result;
        }
        
        public setDataResponse EndsetData(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            setDataResponse _result = ((setDataResponse)(base.EndInvoke("setData", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetList(GetListRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("GetList", _args, callback, asyncState);
            return _result;
        }
        
        public GetListResponse EndGetList(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            GetListResponse _result = ((GetListResponse)(base.EndInvoke("GetList", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginPadCarID(PadCarIDRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("PadCarID", _args, callback, asyncState);
            return _result;
        }
        
        public PadCarIDResponse EndPadCarID(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            PadCarIDResponse _result = ((PadCarIDResponse)(base.EndInvoke("PadCarID", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetWorkingList(GetWorkingListRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("GetWorkingList", _args, callback, asyncState);
            return _result;
        }
        
        public GetWorkingListResponse EndGetWorkingList(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            GetWorkingListResponse _result = ((GetWorkingListResponse)(base.EndInvoke("GetWorkingList", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetEmpDay(GetEmpDayRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("GetEmpDay", _args, callback, asyncState);
            return _result;
        }
        
        public GetEmpDayResponse EndGetEmpDay(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            GetEmpDayResponse _result = ((GetEmpDayResponse)(base.EndInvoke("GetEmpDay", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetEmpMonth(GetEmpMonthRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("GetEmpMonth", _args, callback, asyncState);
            return _result;
        }
        
        public GetEmpMonthResponse EndGetEmpMonth(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            GetEmpMonthResponse _result = ((GetEmpMonthResponse)(base.EndInvoke("GetEmpMonth", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetJson(GetJsonRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("GetJson", _args, callback, asyncState);
            return _result;
        }
        
        public GetJsonResponse EndGetJson(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            GetJsonResponse _result = ((GetJsonResponse)(base.EndInvoke("GetJson", _args, result)));
            return _result;
        }
    }
}

[System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
[System.CodeDom.Compiler.GeneratedCodeAttribute("SlSvcUtil", "5.0.0.0")]
public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
{
    
    private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
    
    public ArrayOfXElement()
    {
    }
    
    public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
    {
        get
        {
            return this.nodesList;
        }
    }
    
    public virtual System.Xml.Schema.XmlSchema GetSchema()
    {
        throw new System.NotImplementedException();
    }
    
    public virtual void WriteXml(System.Xml.XmlWriter writer)
    {
        System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
        for (
        ; e.MoveNext(); 
        )
        {
            ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
        }
    }
    
    public virtual void ReadXml(System.Xml.XmlReader reader)
    {
        for (
        ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
        )
        {
            if ((reader.NodeType == System.Xml.XmlNodeType.Element))
            {
                System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                Nodes.Add(elem);
            }
            else
            {
                reader.Skip();
            }
        }
    }
}
