//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IFileTransportService")]
    public interface IFileTransportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/GetTicketInfo", ReplyAction="http://tempuri.org/IFileTransportService/GetTicketInfoResponse")]
        string GetTicketInfo(string TicketID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/EmpAddWork", ReplyAction="http://tempuri.org/IFileTransportService/EmpAddWorkResponse")]
        string EmpAddWork(string TicketInfoID, string EmpID, string TicketTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/Ordering", ReplyAction="http://tempuri.org/IFileTransportService/OrderingResponse")]
        string Ordering(string EID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/GetEmpWorkingList", ReplyAction="http://tempuri.org/IFileTransportService/GetEmpWorkingListResponse")]
        string GetEmpWorkingList(int EmpID, int TypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/GetStringData", ReplyAction="http://tempuri.org/IFileTransportService/GetStringDataResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        string GetStringData(string Bll, string Exc, object[] par);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/GetLastBackupTime", ReplyAction="http://tempuri.org/IFileTransportService/GetLastBackupTimeResponse")]
        System.DateTime GetLastBackupTime();
        
        // CODEGEN: 消息 FileUploadMessage 的包装名称(FileUploadMessage)以后生成的消息协定与默认值(UploadFile)不匹配
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="UploadFile")]
        void UploadFile(Client.ServiceReference1.FileUploadMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/GetFileList", ReplyAction="http://tempuri.org/IFileTransportService/GetFileListResponse")]
        string[] GetFileList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/GetFile", ReplyAction="http://tempuri.org/IFileTransportService/GetFileResponse")]
        System.IO.Stream GetFile(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="DelFile")]
        void DelFile(string FileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/GetList", ReplyAction="http://tempuri.org/IFileTransportService/GetListResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        System.Data.DataSet GetList(string Bll, string Exc, object[] par);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/GetDSForPrcoce", ReplyAction="http://tempuri.org/IFileTransportService/GetDSForPrcoceResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        byte[] GetDSForPrcoce(string storedProcName, object[] parameters, string tableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/GetSingle", ReplyAction="http://tempuri.org/IFileTransportService/GetSingleResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        object GetSingle(string SQLString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/getZipData", ReplyAction="http://tempuri.org/IFileTransportService/getZipDataResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        byte[] getZipData(string Bll, string Exc, object[] par);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/GetJson", ReplyAction="http://tempuri.org/IFileTransportService/GetJsonResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        byte[] GetJson(string Bll, string Exc, object[] par);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/GetBySql", ReplyAction="http://tempuri.org/IFileTransportService/GetBySqlResponse")]
        byte[] GetBySql(string Sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/GetSqlByByte", ReplyAction="http://tempuri.org/IFileTransportService/GetSqlByByteResponse")]
        byte[] GetSqlByByte(string Sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/GetStringList", ReplyAction="http://tempuri.org/IFileTransportService/GetStringListResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        byte[] GetStringList(string Bll, string Exc, object[] par);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/GetOne", ReplyAction="http://tempuri.org/IFileTransportService/GetOneResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        object GetOne(string Bll, string Exc, object[] par);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/ExecSql", ReplyAction="http://tempuri.org/IFileTransportService/ExecSqlResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        void ExecSql(string Bll, string Exc, object[] par);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/Updata", ReplyAction="http://tempuri.org/IFileTransportService/UpdataResponse")]
        void Updata(string Bll, string Exc, System.Data.DataTable dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/Add", ReplyAction="http://tempuri.org/IFileTransportService/AddResponse")]
        int Add(string Bll, string Exc, System.Data.DataTable dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/CloseClient", ReplyAction="http://tempuri.org/IFileTransportService/CloseClientResponse")]
        void CloseClient();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/GetSysTem", ReplyAction="http://tempuri.org/IFileTransportService/GetSysTemResponse")]
        byte[] GetSysTem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/GetPU", ReplyAction="http://tempuri.org/IFileTransportService/GetPUResponse")]
        byte[] GetPU();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/Backup", ReplyAction="http://tempuri.org/IFileTransportService/BackupResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        object Backup();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/AddLog", ReplyAction="http://tempuri.org/IFileTransportService/AddLogResponse")]
        string AddLog(string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/GetUserName", ReplyAction="http://tempuri.org/IFileTransportService/GetUserNameResponse")]
        string GetUserName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/CarID", ReplyAction="http://tempuri.org/IFileTransportService/CarIDResponse")]
        string CarID(string aaa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/PadCarID", ReplyAction="http://tempuri.org/IFileTransportService/PadCarIDResponse")]
        string PadCarID(string aaa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/SetDataTable", ReplyAction="http://tempuri.org/IFileTransportService/SetDataTableResponse")]
        void SetDataTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/GetDateTime", ReplyAction="http://tempuri.org/IFileTransportService/GetDateTimeResponse")]
        System.DateTime GetDateTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/GetCardMain", ReplyAction="http://tempuri.org/IFileTransportService/GetCardMainResponse")]
        byte[] GetCardMain(int CarID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/GetBoxInfo", ReplyAction="http://tempuri.org/IFileTransportService/GetBoxInfoResponse")]
        string GetBoxInfo(string TicketID);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileUploadMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FileUploadMessage {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileData;
        
        public FileUploadMessage() {
        }
        
        public FileUploadMessage(string FileName, System.IO.Stream FileData) {
            this.FileName = FileName;
            this.FileData = FileData;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileTransportServiceChannel : Client.ServiceReference1.IFileTransportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileTransportServiceClient : System.ServiceModel.ClientBase<Client.ServiceReference1.IFileTransportService>, Client.ServiceReference1.IFileTransportService {
        
        public FileTransportServiceClient() {
        }
        
        public FileTransportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileTransportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileTransportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileTransportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetTicketInfo(string TicketID) {
            return base.Channel.GetTicketInfo(TicketID);
        }
        
        public string EmpAddWork(string TicketInfoID, string EmpID, string TicketTime) {
            return base.Channel.EmpAddWork(TicketInfoID, EmpID, TicketTime);
        }
        
        public string Ordering(string EID) {
            return base.Channel.Ordering(EID);
        }
        
        public string GetEmpWorkingList(int EmpID, int TypeID) {
            return base.Channel.GetEmpWorkingList(EmpID, TypeID);
        }
        
        public string GetStringData(string Bll, string Exc, object[] par) {
            return base.Channel.GetStringData(Bll, Exc, par);
        }
        
        public System.DateTime GetLastBackupTime() {
            return base.Channel.GetLastBackupTime();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Client.ServiceReference1.IFileTransportService.UploadFile(Client.ServiceReference1.FileUploadMessage request) {
            base.Channel.UploadFile(request);
        }
        
        public void UploadFile(string FileName, System.IO.Stream FileData) {
            Client.ServiceReference1.FileUploadMessage inValue = new Client.ServiceReference1.FileUploadMessage();
            inValue.FileName = FileName;
            inValue.FileData = FileData;
            ((Client.ServiceReference1.IFileTransportService)(this)).UploadFile(inValue);
        }
        
        public string[] GetFileList() {
            return base.Channel.GetFileList();
        }
        
        public System.IO.Stream GetFile(string fileName) {
            return base.Channel.GetFile(fileName);
        }
        
        public void DelFile(string FileName) {
            base.Channel.DelFile(FileName);
        }
        
        public System.Data.DataSet GetList(string Bll, string Exc, object[] par) {
            return base.Channel.GetList(Bll, Exc, par);
        }
        
        public byte[] GetDSForPrcoce(string storedProcName, object[] parameters, string tableName) {
            return base.Channel.GetDSForPrcoce(storedProcName, parameters, tableName);
        }
        
        public object GetSingle(string SQLString) {
            return base.Channel.GetSingle(SQLString);
        }
        
        public byte[] getZipData(string Bll, string Exc, object[] par) {
            return base.Channel.getZipData(Bll, Exc, par);
        }
        
        public byte[] GetJson(string Bll, string Exc, object[] par) {
            return base.Channel.GetJson(Bll, Exc, par);
        }
        
        public byte[] GetBySql(string Sql) {
            return base.Channel.GetBySql(Sql);
        }
        
        public byte[] GetSqlByByte(string Sql) {
            return base.Channel.GetSqlByByte(Sql);
        }
        
        public byte[] GetStringList(string Bll, string Exc, object[] par) {
            return base.Channel.GetStringList(Bll, Exc, par);
        }
        
        public object GetOne(string Bll, string Exc, object[] par) {
            return base.Channel.GetOne(Bll, Exc, par);
        }
        
        public void ExecSql(string Bll, string Exc, object[] par) {
            base.Channel.ExecSql(Bll, Exc, par);
        }
        
        public void Updata(string Bll, string Exc, System.Data.DataTable dt) {
            base.Channel.Updata(Bll, Exc, dt);
        }
        
        public int Add(string Bll, string Exc, System.Data.DataTable dt) {
            return base.Channel.Add(Bll, Exc, dt);
        }
        
        public void CloseClient() {
            base.Channel.CloseClient();
        }
        
        public byte[] GetSysTem() {
            return base.Channel.GetSysTem();
        }
        
        public byte[] GetPU() {
            return base.Channel.GetPU();
        }
        
        public object Backup() {
            return base.Channel.Backup();
        }
        
        public string AddLog(string UserName) {
            return base.Channel.AddLog(UserName);
        }
        
        public string GetUserName() {
            return base.Channel.GetUserName();
        }
        
        public string CarID(string aaa) {
            return base.Channel.CarID(aaa);
        }
        
        public string PadCarID(string aaa) {
            return base.Channel.PadCarID(aaa);
        }
        
        public void SetDataTable() {
            base.Channel.SetDataTable();
        }
        
        public System.DateTime GetDateTime() {
            return base.Channel.GetDateTime();
        }
        
        public byte[] GetCardMain(int CarID) {
            return base.Channel.GetCardMain(CarID);
        }
        
        public string GetBoxInfo(string TicketID) {
            return base.Channel.GetBoxInfo(TicketID);
        }
    }
}
